version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on: [zookeeper]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  producer:
    build: ./kafka_streaming
    depends_on: [kafka]
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: ["python", "producer.py"]

  spark:
    build: ./spark_processor
    depends_on: [kafka, mongo]
    user: root
    command: >
      spark-submit
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0
      /app/consumer.py

  dashboard:
    build: ./reviews_dashboard-main
    environment:
      DJANGO_SETTINGS_MODULE: reviews_dashboard.settings
      PYTHONPATH: /app
    command: >
      sh -c "python manage.py collectstatic --no-input &&
            daphne -b 0.0.0.0 -p 8000 reviews_dashboard.asgi:application"
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
